#! /bin/sh

if ! which dch >/dev/null; then
	echo >&2 "please install devscripts"
	exit 1
fi

if ! which debootstrap >/dev/null; then
	echo >&2 "please install debootstrap"
	exit 1
fi

# TODO Remove --nodch when this source gets ready
#exec germinate-update-metapackage --vcs
exec germinate-update-metapackage --vcs --nodch
